Merge AHR-94/input_large_simple to HSA-584/molecules
ahmedmsoliman/Halan-Android-Design-System pull request #12
Opened 2021-09-19 16:38 UTC by mohamed-elshafey-halan

2021-09-20 12:24 UTC, m-taj approved these changes

2021-09-20 12:46 UTC, noureldeen-abouelkassem requested changes
Referencing this issue in MainActivity.kt line 25-27

```
        val configuration: Configuration = resources.configuration
        configuration.setLayoutDirection(Locale("ar"))
        resources.updateConfiguration(configuration, resources.displayMetrics)
```        

I think we shouldn't force Arabic in the app. The way you are trying to force Arabic local in the app is also deprecated. This won't change the local in the app context however in the level of the activity. This will cause the app to mix between the already predefined local from the OS and the overridden one by this method. 

To override the language you have to restart the app this is the 100% working method so far. This will override the local of the app from the beginning by forcing the app to look up the persisted local you have specified before. However, there is no need to do tho. This is just FYI.

I think adding the appropriate strings in Arabic and English will be much enough in such a case like this since this is just a demo app.

As you see enforcing the app language on the level of activity didn't survive us from mixing between RTL and LTR issues since not all of the strings used are localized. 

![Screenshot_1632139724](https://user-images.githubusercontent.com/11015026/134000339-2e6fbaf7-b482-48e7-bdc4-7e4c2697882b.png)

2021-09-20 12:49 UTC, noureldeen-abouelkassem requested changes
It will be better if we showed a description of the regex when the user enables the regex. Instead of telling the user how the input should look like.

2021-09-20 13:22 UTC, noureldeen-abouelkassem requested changes
I think the custom.xml is no longer needed, What do you think?

2021-09-20 13:22 UTC, noureldeen-abouelkassem commented on app/src/main/java/com/example/myapplication/input_large/InputLargeSimpleActivity.kt
> +    }
I would prefer if this be a button on the screen for better UX behavior. What do you think?

2021-09-20 13:22 UTC, noureldeen-abouelkassem commented on app/src/main/res/layout/activity_input_large_simple.xml
> +        android:text="Enable Regex"
A localized string would be better and will survive localization problems as well.

2021-09-20 13:22 UTC, noureldeen-abouelkassem commented on app/src/main/res/layout/activity_input_large_simple.xml
> +</androidx.constraintlayout.widget.ConstraintLayout>
Super 🚀

2021-09-20 13:22 UTC, noureldeen-abouelkassem commented on halan-android-design-system/src/main/java/com/example/halan_android_design_system/molecules/InputLargeSimple.kt
> +class InputLargeSimple(context: Context, attrs: AttributeSet) : TextInputLayout(context, attrs) {
I think it should be InputSimple we shouldn't specify a dimen in the custom view since it is dependent on the dimens.

2021-09-20 13:22 UTC, noureldeen-abouelkassem commented on halan-android-design-system/src/main/java/com/example/halan_android_design_system/molecules/InputLargeSimple.kt
> +    private val focusChangeListener = OnFocusChangeListener { v, hasFocus ->
no need to specify the unused v, it can be replaced with _

2021-09-20 13:22 UTC, noureldeen-abouelkassem commented on halan-android-design-system/src/main/java/com/example/halan_android_design_system/molecules/InputLargeSimple.kt
> +            if (textInputEditText.text?.isNotEmpty() == true)
In Kotlin conventions it will be better if the single If statement were in the same line.

2021-09-20 13:22 UTC, noureldeen-abouelkassem commented on halan-android-design-system/src/main/java/com/example/halan_android_design_system/molecules/InputLargeSimple.kt
> +        textInputEditText.setText(text)
🚨

2021-09-20 13:22 UTC, noureldeen-abouelkassem commented on halan-android-design-system/src/main/java/com/example/halan_android_design_system/molecules/InputLargeSimple.kt
> + */
Thank you, but would you adjust the vertical line that aligns the text width in a file to the default width of Kotlin conventions 😭

2021-09-20 13:22 UTC, noureldeen-abouelkassem commented on halan-android-design-system/src/main/java/com/example/halan_android_design_system/molecules/InputLargeSimple.kt
> +        context.withStyledAttributes(attrs, R.styleable.InputLargeSimple) {
Super 🚀

2021-09-20 13:22 UTC, noureldeen-abouelkassem commented on halan-android-design-system/src/main/java/com/example/halan_android_design_system/molecules/InputLargeSimple.kt
> +                if (!Pattern.matches(it, textValue)) {
Would you use `.not()` instead of the examination mark?

2021-09-20 13:22 UTC, noureldeen-abouelkassem commented on halan-android-design-system/src/main/java/com/example/halan_android_design_system/molecules/InputLargeSimple.kt
> +        applyBaseConfigurations()
Cool method separation, Uncle bob is waving 👋🏻

2021-09-20 13:23 UTC, noureldeen-abouelkassem requested changes
Would you add the 5 dimensions for each of the added vectors since we support SDKs starting from 18 which doesn't support the vectors?

2021-09-20 14:49 UTC, mohamed-elshafey-halan commented on app/src/main/java/com/example/myapplication/input_large/InputLargeSimpleActivity.kt
> +    }
We can do both ✌️

2021-09-20 14:52 UTC, mohamed-elshafey-halan commented on halan-android-design-system/src/main/java/com/example/halan_android_design_system/molecules/InputLargeSimple.kt
> + */
No 🥲

2021-09-21 09:52 UTC, noureldeen-abouelkassem submitted a review, later dismissed

2021-09-21 10:14 UTC, OBeshary commented on app/src/main/java/com/example/myapplication/MainActivity.kt
> +        configuration.setLayoutDirection(Locale("ar"))
add `ar` in constants file

2021-09-21 10:16 UTC, OBeshary commented on app/src/main/java/com/example/myapplication/input_large/InputLargeSimpleActivity.kt
> +    override fun dispatchTouchEvent(event: MotionEvent): Boolean {
would be better if you add a comment on this method as i have no idea what it does 😅

2021-09-21 10:27 UTC, OBeshary commented on halan-android-design-system/src/main/java/com/example/halan_android_design_system/molecules/InputSimple.kt
> +        if (textValue.isNotEmpty() && !hasFocus && !errorHelperText.isNullOrEmpty()) {
[decompose](https://refactoring.guru/decompose-conditional) this logic to a function named `canApplyRegex() : Boolean` for instance.

2021-09-21 10:29 UTC, OBeshary commented on halan-android-design-system/src/main/java/com/example/halan_android_design_system/molecules/InputSimple.kt
> +                if (Pattern.matches(it, textValue).not()) {
separate this into a `TextUtil` or `RegexUtil` as it could be easily unit tested.

2021-09-21 10:30 UTC, OBeshary commented on halan-android-design-system/src/main/java/com/example/halan_android_design_system/molecules/InputSimple.kt
> +        boxStrokeWidthFocused = 1
what does `1` refers to ? it should be added as const with a meaning  name.

2021-09-21 11:56 UTC, mohamed-elshafey-halan commented on app/src/main/java/com/example/myapplication/MainActivity.kt
> +        configuration.setLayoutDirection(Locale("ar"))
The locale changing will be written from scratch again, we are descoped it for now then I'm make a branch for changing the language programmatically from the MainActivity.

2021-09-21 12:25 UTC, noureldeen-abouelkassem approved these changes

2021-09-21 12:28 UTC, OBeshary commented on halan-android-design-system/src/main/java/com/example/halan_android_design_system/molecules/InputSimple.kt
> +    private fun canApplyRegex(textValue: String, hasFocus: Boolean): Boolean {
suggestion : it could be simplified to `private fun canApplyRegex(textValue: String, hasFocus: Boolean) =  textValue.isNotEmpty() && !hasFocus && !errorHelperText.isNullOrEmpty();`

2021-09-21 12:29 UTC, OBeshary commented on halan-android-design-system/src/main/java/com/example/halan_android_design_system/util/RegexUtil.kt
> +    return Pattern.matches(regex, input)
suggestion : it could be simplified to `fun matchRegex(regex: String, input: String) = Pattern.matches(regex, input)`

2021-09-21 12:30 UTC, OBeshary approved these changes

2021-09-21 12:33 UTC, merged