list check. one and two lines
ahmedmsoliman/Halan-Android-Design-System pull request #7
Opened 2021-09-14 12:16 UTC by m-taj

this PR Has a Function Search view component

2021-09-14 13:55 UTC, m-taj commented
@OBeshary @mohamed-elshafey-halan  could you please review his PR

2021-09-14 15:56 UTC, OBeshary commented on app/src/main/java/com/example/myapplication/molecules/list_check_one_line/ListCheckOneLine.kt
>      }
you can reduce the both methods in only one, take a boolean parameter for setting the ui state for instance
` setUI(enabled:Boolean)
{
two_line_container_cl.isClickable = enabled:Boolean
. . . 
}
`

2021-09-14 15:59 UTC, OBeshary commented on app/src/main/java/com/example/myapplication/molecules/list_check_one_line/ListCheckOneLine.kt
> +        }
i see that there is no need for `if else` branches as it has only one line for each condition.

2021-09-14 16:01 UTC, OBeshary commented on app/src/main/java/com/example/myapplication/molecules/list_check_one_line/ListCheckOneLine.kt
> +            description_text_tv.visibility = GONE
i see it could be simplified to `description_text_tv.visibility = if (singleLineFlag) GONE else VISIBLE`

2021-09-14 16:02 UTC, OBeshary commented on app/src/main/res/layout/activity_main.xml
> +            app:isSingleLine="false"
i appreciate using `attrs` to be honest . Gamed 🦾

2021-09-14 16:03 UTC, OBeshary commented on .idea/misc.xml
> -        <entry key="app/src/main/res/layout/list_check_one_and_two_lines.xml" value="0.1" />
`.idea` files shouldn't be pushed

2021-09-14 16:03 UTC, OBeshary commented on app/src/main/res/values/attrs.xml
> +</resources>
i appreciate using attrs to be honest . Gamed 🦾

2021-09-14 16:09 UTC, OBeshary commented on app/src/main/res/layout/list_check_one_and_two_lines.xml
> +        android:textSize="16sp"
why not using the equivalent text style from `styles.xml`

2021-09-14 16:11 UTC, OBeshary commented on app/src/main/java/com/example/myapplication/molecules/list_check_one_line/ListCheckOneLine.kt
> +    private lateinit var currentState: ListItemStates
as suggested in the IDE there is no need to use `lateinit` keyword as it will be initialized in the init block

2021-09-14 16:12 UTC, OBeshary commented on .idea/misc.xml
> +        <entry key="app/src/main/res/layout/list_check_one_and_two_lines.xml" value="0.327445652173913" />
no need to push `.idea` files

2021-09-14 16:13 UTC, OBeshary approved these changes

2021-09-15 13:07 UTC, mohamed-elshafey-halan commented on app/src/main/java/com/example/myapplication/molecules/list_check_one_line/ListCheckOneLine.kt
> +    fun isSingleLine(singleLineFlag: Boolean) {
I think we don’t need to have isSingleLine flag, as by logic If we haven’t secondary text so it should be single line else should have two lines.

2021-09-15 13:08 UTC, mohamed-elshafey-halan commented on app/src/main/java/com/example/myapplication/molecules/list_check_one_line/ListCheckOneLine.kt
> +
I think we should replace activeAndNotSelected, activeAndSelected
, etc… function with changeState(listItemStates: ListItemStates) and remove the redundant functions.

2021-09-15 13:09 UTC, mohamed-elshafey-halan commented on app/src/main/java/com/example/myapplication/molecules/list_check_one_line/ListCheckOneLine.kt
> +                )
should change the checkbox color as well.

2021-09-15 13:15 UTC, m-taj commented on app/src/main/java/com/example/myapplication/molecules/list_check_one_line/ListCheckOneLine.kt
> +
that would be also redundant as there's a function to set state within the ListCheckOneLine Function it self , so maybe just remove the functions from the "ListItemStates" class as those redundant yet keep the functions in the customer view class itself to kind off keep boilerplate code from the user of the component and only give them access to using the states not creating a class of the state and send it through the function as a parameter IYGM ..

2021-09-15 13:20 UTC, mohamed-elshafey-halan commented on app/src/main/java/com/example/myapplication/molecules/list_check_one_line/ListCheckOneLine.kt
> +
Suggestions: 
- I think it's the "View" responsibility to change its state between (checked - unchecked) states, just think of it as the normal CheckBox, and try to imitate its behavior and fields.
-  Should separate the (enabled- disabled) states from (checked - unchecked) states.

2021-09-15 13:21 UTC, mohamed-elshafey-halan requested changes
Please review the comments added in ListCheckOneLine class ✌️

2021-09-16 14:08 UTC, mohamed-elshafey-halan approved these changes

2021-09-16 14:08 UTC, mohamed-elshafey-halan commented on app/src/main/java/com/example/myapplication/molecules/list_item/list_check_one_line/ListCheckOneLine.kt
> +        context.withStyledAttributes(
Cleaner way: 

get rid of ` val attributes = context.obtainStyledAttributes(attrs,R.styleable.ListCheckOneLine, 0, 0)`

and use apply as the following -> 

context.obtainStyledAttributes(attrs,R.styleable.ListCheckOneLine, 0, 0).apply {
            -------- Rest of code here -------
            recycle()
        }

2021-09-16 14:47 UTC, m-taj commented on app/src/main/java/com/example/myapplication/molecules/list_item/list_check_one_line/ListCheckOneLine.kt
> + *
appreciate it , will look for a way to reference the functions part

2021-09-19 15:08 UTC, noureldeen-abouelkassem requested changes
Would you follow the branch conventions so the rules of merging got applied by default on this branch?

`(feature|bugfix|improvement|task|subtask|prerelease|release|hotfix)\/[A-Z]+[-]+[0-9]+\/[A-Za-z0-9-]`

2021-09-20 12:03 UTC, closed without merging